//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyanskiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolyanskiyTestEntities : DbContext
    {
        public PolyanskiyTestEntities()
            : base("name=PolyanskiyTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Наборы_для_творчества> Наборы_для_творчества { get; set; }
        public virtual DbSet<Пункты_выдачи> Пункты_выдачи { get; set; }
    }
}
