//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyanskiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int id { get; set; }
        public string Состав_заказа { get; set; }
        public string Дата_заказа { get; set; }
        public string Дата_доставки { get; set; }
        public Nullable<int> Пункт_выдачи { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> Код_для_получения { get; set; }
        public string Статус_заказа { get; set; }
    }
}
