//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyanskiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Наборы_для_творчества
    {
        public int id { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Еденица_измерения { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public Nullable<int> Скидка { get; set; }
        public string Производитель { get; set; }
        public string Поставщик { get; set; }
        public string Категория_товара { get; set; }
        public Nullable<int> Действующая_скидка { get; set; }
        public Nullable<int> Количество_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    }
}
